### ISSUE TITLE
Why are SSSOM mappings not included in OMO build/release?

### ISSUE THREAD

**Issue by cthoyt** [information-artifact-ontology/ontology-metadata#130]
Originally stated in https://github.com/information-artifact-ontology/ontology-metadata/commit/83e0301da8b2d924b60eed39305e3f15a068891f#commitcomment-113398830:

> it doesn't look like the mappings from https://github.com/information-artifact-ontology/ontology-metadata/blob/master/src/ontology/components/omo-to-external.tsv got pulled in to this release

**Comment by matentzn** [comment]
This repo is not set up for sssom inclusion yet.. Does the absence of those mappings in omo.owl cause a problem for you now? Blocker I mean?

**Comment by cthoyt** [comment]
it's not a blocker since I currently maintain these mappings in https://github.com/biopragmatics/bioontologies/blob/main/src/bioontologies/upgrade/data.tsv, but ideally i want to do this curation in OMO instead of maintaining it as a 3rd party resource

**Comment by matentzn** [comment]
Why isnt it sufficient to supply the sssom files, versioned, in the repo? Is it necessary to add those mappings into the OMO vocab? Remember that if we add them, we add some pretty bad signature to the small OMO ontology, which we really need to keep small and nimble.

**Comment by matentzn** [comment]
For some ontologies, I definitely want to add the SSSOM mappings, but this one here is a bit of an odd one out. I am definitely open to add them, just need to be careful about not making the OMO adoption process harder.

**Comment by cthoyt** [comment]
okay then I think we can close this issue. Thanks for the explanation
