### ISSUE TITLE
Request for adding property `Previous Name` to OMO

### ISSUE THREAD

**Issue by cthoyt** [information-artifact-ontology/ontology-metadata#139]
### Label

Previous Name

### Definition of the property

This is an additional synonym type that is used for synonyms that used to be the primary label. Several resources use this, notably HGNC

### Parent property

http://www.geneontology.org/formats/oboInOwl#SynonymType

### What is the range of the property in question?

xsd:string

### Examples of use

MAPT, the gene that encodes the Tau protein, has a previous name DDPAC. Note: in this case, the name type is more specifically the gene symbol

### Motivation to add

Following #124 and #133, this is another useful synonym type that can be used to help standardize hash urls used throughout OBO Foundry

### ORCID, ROR or Wikidata identifier of the contributor

https://orcid.org/0000-0003-4423-4370

### OMO Checklist

- [X] I believe the property is generally useful beyond my specific ontology needs.
- [X] There is no other property in OMO that covers the same use case.

**Comment by matentzn** [comment]
I think this is a reasonable request! Would you be able to make a PR?
