### ISSUE TITLE
Request for adding property `legal name` to OMO

### ISSUE THREAD

**Issue by cthoyt** [information-artifact-ontology/ontology-metadata#141]
### Label

legal name

### Definition of the property

A synonym that is the legal entity name

### Parent property

http://www.geneontology.org/formats/oboInOwl#SynonymType

### What is the range of the property in question?

xsd:string

### Examples of use

The legal name for Harvard University (https://ror.org/03vek6s52) is `President and Fellows of Harvard College`

### Motivation to add

ROR has a complicated data model that has a specific field for legal names. It wants to combine all synonyms into a single field, but still annotate what kind of synonym is each. This property would enable this.

### ORCID, ROR or Wikidata identifier of the contributor

https://orcid.org/0000-0003-4423-4370

### OMO Checklist

- [X] I believe the property is generally useful beyond my specific ontology needs.
- [X] There is no other property in OMO that covers the same use case.

**Comment by matentzn** [comment]
I am fine with accepting a PR about this!
