### ISSUE TITLE
Request for adding property symbol (IAO:0000028) to OMO

### ISSUE THREAD

**Issue by anitacaron** [information-artifact-ontology/ontology-metadata#144]
### IRI

http://purl.obolibrary.org/obo/IAO_0000028

### Label

symbol

### Definition of the property

An information content entity that is a mark(s) or character(s) used as a conventional representation of another entity.

### What is the range of the property in question?

xsd:string

### Examples of use

a serial number such as "12324X"; a stop sign; a written proper name such as "OBI"

### Motivation to add

This is officially a class in IAO, and we're using it as an annotation in CL. We imported IAO and added the annotation type definition. However, people are having problems loading the CL ontology using owlready2 0.38. Check issue https://github.com/obophenotype/cell-ontology/issues/2080

### ORCID, ROR or Wikidata identifier of the contributor

https://orcid.org/0000-0002-6523-4866

### OMO Checklist

- [X] I believe the property is generally useful beyond my specific ontology needs.
- [X] There is no other property in OMO that covers the same use case.

**Comment by matentzn** [comment]
@zhengj2007 what is the process of adding IAO terms to OMO?

Are they imported and the source of truth stays with IAO, or are they adopted and OMO becomes the new source of truth?

**Comment by zhengj2007** [comment]
@matentzn Sorry I missed the notification. 
For the IAO terms moved to OMO, we just removed the terms from the IAO and added them in the OMO. The terms don't have 'import from' annotation property. But it needs to update the purl redirect to  link the term to the OMO rather than the IAO. James helped on it. I made the IAO release just after each OMO release for consistency.

**Comment by matentzn** [comment]
Thanks @zhengj2007 

For this specific term, is it ok to migrate it then from IAO to OMO?

**Comment by zhengj2007** [comment]
@matentzn I am fine with it. Please let me know when you make the OMO release, then I will remove the term and make IAO release. Thanks!

**Comment by matentzn** [comment]
@anitacaron I wont get to this any time soon, feel free if this is important to you to add the term by yourself, including all metadata from IAO.

**Comment by zhengj2007** [comment]
Sorry for missing the details of the request. I don't think it is correct to move an IAO class to OMO as an annotation property.

I think there is the need to have 'symbol' class. And the term has some subclasses and been widely used. If we need an annotation property 'symbol'. I propose to add a new annotation property and use other label, such as, 'has symbol'.

@anitacaron @matentzn

**Comment by anitacaron** [comment]
I agree with your solution, @zhengj2007. Which OMO ID should I create it?

**Comment by zhengj2007** [comment]
@anitacaron I checked the OMO by opening omo-edit.owl using protege. Some ID ranges have been assigned to some editors and OBO Foundry Committee. 

I think you may add your name and assign an ID range to yourself. But it would better to check with @matentzn.

**Comment by cthoyt** [comment]
I just noticed this got merged, but I am totally not understanding the example. Can you give a concrete example where this synonym property would get used on a specific class in some OBO ontology?

**Comment by anitacaron** [comment]
The property has been used in CL, for example, the term [Lamp5-like Pax6 primary motor cortex GABAergic interneuron (Mmus)](https://www.ebi.ac.uk/ols4/ontologies/pcl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPCL_0011001)

<img width="284" alt="Screen Shot 2024-11-05 at 07 17 35" src="https://github.com/user-attachments/assets/4a4ce4c1-800d-4486-bbde-fdbca4934717">

**Comment by cthoyt** [comment]
Are HGNC gene symbols also falling under this? Maybe you can give me another example from another ontology so I can try and better understand what this is

**Comment by cmungall** [comment]
This seems a bit odd. It’s a synonym composed of symbols and labels but is
not itself a symbol
