### ISSUE TITLE
Request for adding property 'Latin term' to OMO

### ISSUE THREAD

**Issue by bvarner-ebi** [information-artifact-ontology/ontology-metadata#146]
### IRI

http://purl.obolibrary.org/obo/uberon/core#LATIN; http://purl.obolibrary.org/obo/uberon#LATIN

### Label

Latin term

### Definition of the property

A synonym type for describing Latin term synonyms.

### Parent property

SynonymType

### What is the range of the property in question?

xsd:string

### Examples of use

```
[Term]
id: UBERON:0001728
name: nasopharynx
def: "The section of the pharynx that lies above the soft palate." [MGI:cwg, MP:0002251]
...
synonym: "pars nasalis pharyngis" RELATED Latin term 
```

### Motivation to add

Context: https://github.com/obophenotype/uberon/issues/1727, https://github.com/obophenotype/cell-ontology/issues/893

At present, there exists more than one synonym type annotation property in OBO ontologies to represent a Latin term: [LATIN](http://purl.obolibrary.org/obo/uberon/core#LATIN) and '[latin term](http://purl.obolibrary.org/obo/uberon#LATIN)'.

This request is part of an effort to standardise synonym type annotation properties across OBO ontologies.

### ORCID, ROR or Wikidata identifier of the contributor

n/a

### OMO Checklist

- [X] I believe the property is generally useful beyond my specific ontology needs.
- [X] There is no other property in OMO that covers the same use case.

**Comment by matentzn** [comment]
Hey @bvarner-ebi can you provide a bit more formal definition? If you phrase it like this it sounds more like a translation then a synonym. What exactly do you mean by "Latin" - you mean the scientific name?

**Comment by bvarner-ebi** [comment]
Thank you for the follow up, @matentzn.

The intent is to capture the original meaning of the annotation properties noted in the original comment, but unfortunately neither of those properties have text definitions.

This text definition is an assumption of the original intent:

A synonym type for describing synonyms that are written in the Latin language, typically based on a scientific standard. This includes, for example, Latin entries of the terms included in Terminologia Anatomica.

**Comment by matentzn** [comment]
Ok. I think to move forward on this we need a clearer picture of what the original intend was. Can you share this issue on slack (Uberon channel) and ask Chris about the exact purpose here, i.e. capture the scientific name or providing a LATIN language translations?

**Comment by cmungall** [comment]
I'm not sure if it helps to think of these are translations. For centuries the official names of anatomical entities have been latin, and this is enshrined in Terminologica Anatomica (TA), the LATIN terms in Uberon are probably best thought of as historic official TA names that have historically been Latin. IFPAA basically split in the question of whether it should be Latin moving forward.

**Comment by cmungall** [comment]
It looks like uberon has a mix of official TA names (designated FMA:TA) and other latin variants sourced from Wikipedia

**Comment by bvarner-ebi** [comment]
> It looks like uberon has a mix of official TA names (designated FMA:TA) and other latin variants sourced from Wikipedia

Thanks for the feedback, @cmungall. Based on my cursory review, I found the same in Uberon. Do you think this proposed definition for a new OMO term, 'Latin term', is sufficient?

"A synonym type for describing synonyms that are written in the Latin language, typically based on a scientific standard. This includes, for example, Latin entries of the terms included in Terminologia Anatomica."

**Comment by bvarner-ebi** [comment]
Is anything else required to advance this issue?

**Comment by matentzn** [comment]
Afaics, this is good to go. 

Here is an example PR if you want to advance this: https://github.com/information-artifact-ontology/ontology-metadata/pull/150/files

**Comment by cthoyt** [comment]
@bvarner-ebi if you don't have time, I can prepare a PR on your behalf tomorrow

**Comment by bvarner-ebi** [comment]
> @bvarner-ebi if you don't have time, I can prepare a PR on your behalf tomorrow

@cthoyt, thank you, that would be great.
