### ISSUE TITLE
NTR: `International Nonproprietary Name`

### ISSUE THREAD

**Issue by cthoyt** [information-artifact-ontology/ontology-metadata#149]
> Not doing country specific for the generic property sounds good to me.
>
> I like the idea of 'layperson synonym' but the label bothers me, e.g. paracetamol/acetaminophen is really the name used by pharmacists etcs, see https://en.wikipedia.org/wiki/Paracetamol#Naming. 
>
> What about something similar to https://en.wikipedia.org/wiki/International_nonproprietary_name? I think that may be what we are looking for here.

_Originally posted by @mcourtot in https://github.com/information-artifact-ontology/ontology-metadata/issues/148#issuecomment-1740773560_
            

As a follow-up to #148, I also want to add a synonym type for INNs, which are also used in ChEBI and I think need a bit less discussion than brand names

**Comment by matentzn** [comment]
`International Nonproprietary Name` sounds very general for something you want to make a subclass of chemical synonym.. It may be misused unless the label clearly denotes that this is restricted to chemicals..

Unless of course there is a reason for just using INN for anything, including non-chemical things?

**Comment by matentzn** [comment]
Any way we can change the label to make it more descriptive? Like adding (INN) in brackets to say that it is an official designation, or some such? (I do not know if this is a good idea!!)

If not, just get a bit of a positive vibe from @cmungall and I am ok with it as well!

**Comment by cthoyt** [comment]
It's uppercased, this typically implies it's a proper noun. In the chemistry world, this is a pretty well known designation, and having it fall under the "chemical synonym" hierarchy also gives additional context quickly.

I also mentioned I wanted to add a synonym for it to give additional context, but am not sure the best way to extend the curation template
