### ISSUE TITLE
How to add synonyms to synonym types?

### ISSUE THREAD

**Issue by cthoyt** [information-artifact-ontology/ontology-metadata#155]
I would like to be able to add synonyms for the annotation properties. For example:

1. INN as a synonym of International Non-proprietary Name
2. Based on the conversation at https://obo-communitygroup.slack.com/archives/C01R2D66249/p1697739460459709, I think it makes sense to add "acronym" as a narrow synonym of "abbreviation".

Since the term for abbreviation was originally curated in a template, what's the best way to add this synonym?

**Comment by cthoyt** [comment]
@matentzn I think you are the best to answer this

**Comment by matentzn** [comment]
The vote in slack is not sufficient to make this change here in OMO (it was to make a call in the NCBITaxon issue).. There a stakeholders of OMO and people here that I know for a fact are against this decision, and are not on slack. For this, we need to create a new vote first. Feel free to call a vote in the appropriate issue (maybe the one on acronyms).

After that, we can add a synonym column to the template and add the synonym there (as you say, with narrowSynonym) I assume.

**Comment by cthoyt** [comment]
Okay, I also want to make "INN" as a synonym for OMO:0003010, so maybe I can get going on the technical part as well.
