### ISSUE TITLE
Remove obsolete `omo-base.owl` from repository

### ISSUE THREAD

**Issue by anitacaron** [information-artifact-ontology/ontology-metadata#163]
This artefact has been used in OBO DASHBOARD because it first tries to get the base file, but in this case, it's not part of the releases anymore.

<img width="760" alt="Screenshot 2023-12-13 at 09 49 12" src="https://github.com/information-artifact-ontology/ontology-metadata/assets/2208124/d023fa50-cc94-48af-9238-6491d940832a">

**Comment by matentzn** [comment]
The base is not part of the OMO release anymore? Oops

**Comment by anitacaron** [comment]
It makes sense because of all the external terms or you should add all namespace in omo-odk.yml
