### ISSUE TITLE
broad synonym

### ISSUE THREAD

**Issue by zhengj2007** [information-artifact-ontology/ontology-metadata#18]
_From @zhengj2007 on July 31, 2015 21:39_

_From [dosu...@gmail.com](https://code.google.com/u/102674886352087815907/) on March 10, 2011 09:56:42_

_label for the new term_

Broad synonym

_textual definition_

def: "Information artifact that links an ontology term to a term in language that, within some specified publication or discipline, has a broader set of referents then the ontology term." Please provide any additional information below. (e.g., proposed position in the IAO hierarchy) is_a: synonym

_Original issue: http://code.google.com/p/information-artifact-ontology/issues/detail?id=104_

_Copied from original issue: information-artifact-ontology/IAO#104_

**Comment by cmungall** [comment]
is there an action or a proposal here?

**Comment by zhengj2007** [comment]
I think this is the proposal: https://github.com/information-artifact-ontology/ontology-metadata/issues/9
