### ISSUE TITLE
language setting of values of annotationProperty

### ISSUE THREAD

**Issue by zhengj2007** [information-artifact-ontology/ontology-metadata#27]
By default, OBO foundry ontologies are English. Current more and more ontologies are translated into other languages, like Spanish, French and Chinese. 

Shall we set the policy to require language settings for annotations (at lease for label and definition)?

**Comment by cmungall** [comment]
is this a question about OBO policy or about IAO?

OBO could definitely do a better job here

**Comment by zhengj2007** [comment]
Discussed on 2018-12-04 OFOC call. 

It’s an issue hard to solve now. Need to propose an approach then decide anything need to do on tagging terms using annotation.

**Comment by jamesaoverton** [comment]
I don't understand what "language setting" means. RDF has [language-tagged strings](
https://www.w3.org/TR/rdf11-concepts/#dfn-language-tagged-string) and other literals. OWL inherits these from RDF.
