### ISSUE TITLE
Create AP for linking a class or object to a discussion/call for comments/github ticket

### ISSUE THREAD

**Issue by cmungall** [information-artifact-ontology/ontology-metadata#33]

**Comment by zhengj2007** [comment]
Should we close it?

**Comment by matentzn** [comment]
I will close this, recommending (this is what we do) to use `rdfs:seeAlso`.

**Comment by StroemPhi** [comment]
Isn't this the same as http://purl.obolibrary.org/obo/IAO_0000233 (term tracker item)?

**Comment by matentzn** [comment]
Yes, it is - I am on a rampage though to try and get people to use less OBO-syncratic and more widely used vocabs. Using IAO:0000233 is not wrong. Continue to do so if you wish! Linking GitHub comments is a lower priority right now, and this can be changed fairly easily later.
