### ISSUE TITLE
New annotation property - 'may be identical to'

### ISSUE THREAD

**Issue by zhengj2007** [information-artifact-ontology/ontology-metadata#40]
_From @dosumis on September 12, 2018 13:9_

VFB is dealing with very large numbers of neuronal cell type terms from different sources. Increasingly we have evidence from papers or analysis suggesting that two separately defined terms may actually refer to the same type of neuron.  Where such assertions are uncertain, we would like to use an annotation property capture them. The resulting annotation axiom can then be further annotated with provenance info (reference, comment, curator, evidence type etc).  This approach will allow us to display potential mappings to users and to track evidence that may eventually be used to inform decisions to merge terms.  This is likely to be generally useful in cell ontology work given rapid advances in single cell biology.

_Copied from original issue: information-artifact-ontology/IAO#207_

**Comment by zhengj2007** [comment]
@dosumis I think it may belong to ontology-metadata repository, https://github.com/information-artifact-ontology/ontology-metadata/issues.

Do you mind moving the tracker there?

**Comment by zhengj2007** [comment]
_From @cmungall on September 12, 2018 16:4_

or just using skos?

**Comment by zhengj2007** [comment]
_From @dosumis on September 13, 2018 8:53_

> or just using skos?

Do you have any particular SKOS property in mind?  I don't feel that any of the [SKOS mapping relations](https://www.w3.org/TR/skos-reference/#mapping)  quite work.  I actually think a realist way of describing the problem works well in this case:

Neurons types are natural types (Universal is too loaded).  There are multiple ways to uniquely identify a neuron type by some combination of the properties they have.  When we are truly confident that two or more terms, with different definitions, refer to the same type, then we will merge.  Until then we need to relate these terms in some way and track assertions & evidence that they refer to the same type.  See example here: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/pull/347#issuecomment-420634805

  - A neuron type found in a screen for descending neurons has similar location and morphology to a neuron type found by a group studying octopaminergic neurons and another discovered by a group studying fruitless expression neurons.

SKOS, OTOH has mapping relations like this:

The property skos:closeMatch is used to link two concepts that are sufficiently similar that they can be used interchangeably in some information retrieval applications. In order to avoid the possibility of "compound errors" when combining mappings across more than two concept schemes, skos:closeMatch is not declared to be a transitive property.

I'm not confident that the neuron types in the example could be used interchangeably in some information retrieval applications.  Either they are the same type or they are not, we're just not confident enough to say so yet.  Further experiments (an experiment assaying expression of the driver used find the descending neuron + fruitless / Octopaminergic neuron marker) are needed.

(I'm not completely dogmatic about this natural-type framing though.  We could decide by fiat that the descending neuron term covers all with that morphology, making the other two subclasses - but we'd still merge if all members of the class defined by morphology turned out to be fruitless expressing octopaminergic neurons)

**Comment by zhengj2007** [comment]
_From @cmungall on September 13, 2018 22:15_

OK, seems new property is justified - do you want to make a PR, or are you doing these @zhengj2007 ?

**Comment by zhengj2007** [comment]
@cmungall what does PR mean?

**Comment by zhengj2007** [comment]
_From @dosumis on September 14, 2018 8:22_

I'll do it.

**Comment by zhengj2007** [comment]
_From @dosumis on September 21, 2018 16:56_

@zhengj2007 pull request link above.  Can you check the diff and approve if you think OK.

@Clare72 please see pull request for new IRI.

**Comment by zhengj2007** [comment]
@dosumis The label and definition looks good to me. 

Could you please also add following annotation properties?
1. term editor (IAO_0000117): your name
2. term tracker item (IAO_0000233): https://github.com/information-artifact-ontology/ontology-metadata/issues/40
3. ontology term requester (IAO_0000234): VFB

Thanks!

**Comment by zhengj2007** [comment]
This term was assign ID as: IAO_0006011

Any thought on what IAO ID range should we reserve for ontology metadata?
@cmungall @alanruttenberg @jamesaoverton @mcourtot

**Comment by dosumis** [comment]
> Could you please also add following annotation properties?
> ...

Done  https://github.com/information-artifact-ontology/ontology-metadata/pull/39/files

**Comment by zhengj2007** [comment]
Annotation property 'may be identical to' is added: 59a20a85783fde176b32fe30004185b1337a3d5f
