### ISSUE TITLE
OBO term creation date question

### ISSUE THREAD

**Issue by matentzn** [information-artifact-ontology/ontology-metadata#52]
@zhengj2007 @cmungall 

We were discussing the inconsistent annotation of terms with either `dc:dateTime` or `oio:creation_date` across OBO ontologies. Which is the correction relation we should be using to denote creation time? Whatever it is, I will promote across my community. Thank you!

**Comment by matentzn** [comment]
Either it seems to be a difficult question or no one knows?

**Comment by wdduncan** [comment]
I've just been using dcterms:date as an annotation on the term. But `oio:creation_date` may work better ... more explicit.

**Comment by cmungall** [comment]
GO uses oio:

```
Creator property Add http://www.geneontology.org/formats/oboInOwl#created_by
Creator value Select Use user name
Check Annotate new entities with creation date/time box
Date property Add http://www.geneontology.org/formats/oboInOwl#creation_date
Date value format Select ISO-8601
```

note that only oio would yield obof tags:

```
id: GO:0003157
name: endocardium development
namespace: biological_process
def: "The process whose specific outcome is the progression of the endocardium over time, from its formation to the mature structure. The endocardium is an anatomical structure comprised of an endothelium and an extracellular matrix that forms the innermost layer of tissue of the heart, and lines the heart chambers." [GOC:mtg_heart]
is_a: GO:0032502 ! developmental process
is_a: GO:0048856 ! anatomical structure development
intersection_of: GO:0048856 ! anatomical structure development
intersection_of: results_in_development_of UBERON:0002165 ! endocardium
relationship: part_of GO:0007507 ! heart development
created_by: dph
creation_date: 2009-10-01T12:42:27Z
```

although on option is to translate to oio prior to obof conversion, but IMHO this is awkward and introduces potential confusion

**Comment by pbuttigieg** [comment]
ENVO now defaults to dc terms:

![image](https://user-images.githubusercontent.com/2276146/90775398-16793e00-e2f9-11ea-9860-a7e95e7f5526.png)



There's a bunch of OBO-specific castings of things like this (including SKOS-like synonyms) which hurts our global interoperability.

**Comment by mcourtot** [comment]
I like creation_date - as mentioned by @wdduncan above it is less ambiguous; date could be last update date or else for example. 

@cmungall what's the status of oboInOwl? I was under the impression that it would be retired and superseded by IAO, OBI or else, but I'm not sure whether this is true. It does seem a little bit messy to have a bunch of resources for what we're hoping to be common annotation properties.

**Comment by cmungall** [comment]
This is a dupe, let's use

- #63
