### ISSUE TITLE
AnnotationProperty -- broad alternate label

### ISSUE THREAD

**Issue by zhengj2007** [information-artifact-ontology/ontology-metadata#9]
_From @zhengj2007 on July 31, 2015 21:38_

_From [shahid.m...@gmail.com](https://code.google.com/u/110958216731968693037/) on February 01, 2011 11:55:16_

Please indicate the label for the new term broad alternate label Please provide a textual definition an alternate label for a class C that denotes something more general than C Please add an example of usage for that term Please provide any additional information below. (e.g., proposed position in the IAO hierarchy) subannotationpropertyof: alternate label

xref: obo-format:BROAD

_Original issue: http://code.google.com/p/information-artifact-ontology/issues/detail?id=95_

_Copied from original issue: information-artifact-ontology/IAO#95_

**Comment by zhengj2007** [comment]
_From [mcour...@gmail.com](https://code.google.com/u/116795168307825520406/) on May 25, 2011 14:19:38_

see https://code.google.com/p/information-artifact-ontology/issues/detail?id=104

**Status:** WontFix

**Comment by nicolevasilevsky** [comment]
@zhengj2007 this was marked wontfix in google code. 
On the call today, I added 'has broad synonym' on PR: https://github.com/information-artifact-ontology/ontology-metadata/pull/66

Do you think that covers this?
(same thing with https://github.com/information-artifact-ontology/ontology-metadata/issues/12, https://github.com/information-artifact-ontology/ontology-metadata/issues/10, https://github.com/information-artifact-ontology/ontology-metadata/issues/11, https://github.com/information-artifact-ontology/ontology-metadata/issues/9)

**Comment by matentzn** [comment]
Can we close this in favour of #18 ?

**Comment by zhengj2007** [comment]
@matentzn Fine with me.
